version: "3"

services:

  runtime-setup:
    image: swift-package-collection-generator:20.04-5.6
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.6-focal"
        ubuntu_version: "focal"

  test:
    image: swift-package-collection-generator:20.04-5.6
    environment: []
      #- SANITIZER_ARG=--sanitize=thread

  shell:
    image: swift-package-collection-generator:20.04-5.6
